# Generated by Django 3.2.6 on 2021-10-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='anh')),
                ('sanpham', models.TextField()),
                ('gia', models.TextField()),
            ],
        ),
    ]
